apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trusted-artifact-signer-triggerbinding
spec:
  params:
    - name: fulcio-url
      value: https://fulcio.apps.ocp4.whatever.out-of-my-head.de/
    - name: fulcio-crt-pem-url
      value: https://tuf.apps.ocp4.whatever.out-of-my-head.de/targets/fulcio-cert
    - name: rekor-url
      value: https://rekor.apps.ocp4.whatever.out-of-my-head.de/
    - name: issuer-url
      value: https://keycloak-keycloak-system.apps.ocp4.whatever.out-of-my-head.de/auth/realms/sigstore
    - name: tuf-mirror
      value: https://tuf.apps.ocp4.whatever.out-of-my-head.de/
    - name: tuf-root
      value: https://tuf.apps.ocp4.whatever.out-of-my-head.de/root.json
    - name: rekor-public-key
      value: https://tuf.apps.ocp4.whatever.out-of-my-head.de/targets/rekor.pub
    - name: ctfe-public-key
      value: https://tuf.apps.ocp4.whatever.out-of-my-head.de/targets/ctfe.pub
