apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - build-and-sign-pipeline.yaml
  - build-and-sign-triggerbinding.yaml
  - build-and-sign-triggertemplate.yaml
  - build-and-sign-el.yaml
  - build-and-sign-el-route.yaml
  - tektonChain.yaml
