apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  name: chain
spec:
  targetNamespace: openshift-pipelines
  artifacts.oci.format: simplesigning
  artifacts.oci.storage: oci
  artifacts.oci.signer: x509
  artifacts.taskrun.format: in-toto 
  artifacts.taskrun.storage: oci
  artifacts.taskrun.signer: x509
  transparency.enabled: true
  transparency.url: https://rekor.apps.ocp4.whatever.out-of-my-head.de
  signers.x509.fulcio.enabled: true
  signers.x509.fulcio.address: https://fulcio.apps.ocp4.whatever.out-of-my-head.de
  signers.x509.fulcio.issuer: https://keycloak-keycloak-system.apps.ocp4.whatever.out-of-my-head.de/auth/realms/sigstore
